export const cryptoTokens = [
  { id: 1, symbol: 'VET', name: 'VeChain' },
  { id: 2, symbol: 'DEXE', name: 'DeXe' },
  { id: 3, symbol: 'APT', name: 'Aptos' },
  { id: 4, symbol: 'OP', name: 'Optimism' },
  { id: 5, symbol: 'LINK', name: 'Chainlink' },
  { id: 6, symbol: 'NEAR', name: 'NEAR Protocol' },
  { id: 7, symbol: 'OKB', name: 'OKB' },
  { id: 8, symbol: 'BNB', name: 'Binance Coin' },
  { id: 9, symbol: 'WRX', name: 'WazirX' },
  { id: 10, symbol: 'BCH', name: 'Bitcoin Cash' },
  { id: 11, symbol: 'XMR', name: 'Monero' },
  { id: 12, symbol: 'LTC', name: 'Litecoin' },
  { id: 13, symbol: 'INJ', name: 'Injective' },
  { id: 14, symbol: 'ADA', name: 'Cardano' },
  { id: 15, symbol: 'UNI', name: 'Uniswap' },
  { id: 16, symbol: 'SOL', name: 'Solana' },
  { id: 17, symbol: 'DYDX', name: 'dYdX' },
  { id: 18, symbol: 'ETC', name: 'Ethereum Classic' },
  { id: 19, symbol: 'AAVE', name: 'Aave' },
  { id: 20, symbol: 'TKX', name: 'Tokenize Xchange' },
  { id: 21, symbol: 'TON', name: 'Toncoin' },
  { id: 22, symbol: 'USDC', name: 'USD Coin' },
  { id: 23, symbol: 'AVAX', name: 'Avalanche' },
  { id: 24, symbol: 'EGLD', name: 'MultiversX' },
  { id: 25, symbol: 'MATIC', name: 'Polygon' },
  { id: 26, symbol: 'TRX', name: 'TRON' },
  { id: 27, symbol: 'FTN', name: 'Fasttoken' },
  { id: 28, symbol: 'HBAR', name: 'Hedera' },
  { id: 29, symbol: 'ARB', name: 'Arbitrum' },
  { id: 30, symbol: 'SHIB', name: 'Shiba Inu' },
  { id: 31, symbol: 'COMP', name: 'Compound' },
  { id: 32, symbol: 'SUI', name: 'Sui' },
  { id: 33, symbol: 'GT', name: 'GateToken' },
  { id: 34, symbol: 'XLM', name: 'Stellar' },
  { id: 35, symbol: 'SKL', name: 'Skale' },
  { id: 36, symbol: 'ATOM', name: 'Cosmos Hub' },
  { id: 37, symbol: 'RAY', name: 'Raydium' },
  { id: 38, symbol: 'FIL', name: 'Filecoin' },
  { id: 39, symbol: 'FLM', name: 'Flamingo' },
  { id: 40, symbol: 'MANA', name: 'Decentraland' },
  { id: 41, symbol: 'AXL', name: 'Axelar' },
  { id: 42, symbol: 'HNT', name: 'Helium' },
  { id: 43, symbol: 'ENJ', name: 'Enjin' },
  { id: 44, symbol: 'LEO', name: 'UNUS SED LEO' },
  { id: 45, symbol: 'AIOZ', name: 'AIOZ Network' },
  { id: 46, symbol: 'APE', name: 'ApeCoin' },
  { id: 47, symbol: 'JST', name: 'JUST' },
  { id: 48, symbol: 'KAVA', name: 'Kava' },
  { id: 49, symbol: 'RSR', name: 'Reserve Rights' },
  { id: 50, symbol: 'RUNE', name: 'THORChain' },
  { id: 51, symbol: 'STRK', name: 'Starknet' },
  { id: 52, symbol: 'CFX', name: 'Conflux' },
  { id: 53, symbol: 'SUN', name: 'SUN (TRON)' },
  { id: 54, symbol: 'PYTH', name: 'Pyth Network' },
  { id: 55, symbol: 'GMX', name: 'GMX' },
  { id: 56, symbol: 'TIA', name: 'Celestia' },
  { id: 57, symbol: 'LDO', name: 'Lido DAO' },
  { id: 58, symbol: 'AR', name: 'Arweave' },
  { id: 59, symbol: 'OM', name: 'Mantra' },
  { id: 60, symbol: 'ICP', name: 'Internet Computer' },
]; 